src/get_gateway-linux.h

Changed "dateway" to "gateway"

Fixing typo in gateway MAC error message

---

src/probe_modules/module_udp.c

Many UDP protocols respond from a port other than the one that was scanned. The dport validation logic makes sense for ICMP, but not for the UDP response itself, since it would drop valid responses.

Stop dropping UDP replies coming from non-destination ports

---

src/recv-pcap.c

This is a retake of issue #246 that prefixes the pcap filter with a rule dropping all traffic that does not originate from the detected or configured gateway MAC address. This seems to comprehensively fix the issue with the receive functions seeing sent traffic.

Ignore traffic that doesn't come from the gateway

---

src/send.c

I want to use zmap but with small rates (of a few packets per second). So I needed to fix the send_loop.
If the packet rate is smaller than the number of thread the interval gets rounded to 0 and is ignored than. The second problem is that the busy loop consumes too much CPU. So I use nanosleep to wait the expected time. This is an additional code path in send_run but shouldn't not matter performance wise due to branch prediction. Also packet rates smaller than number of threads are now possible.
I left the rest of the code unchanged as much as possible because I am not sure if something relies on the divide to 0 behavior.

Change send_run to better handle small rates.

---

src/monitor.c

src/monitor.c: In function 'export_stats':
src/monitor.c:188:13: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
if (!intrnl->min_hitrate_start) {
^
src/monitor.c:194:9: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
if (intrnl->min_hitrate_start) {
---
Notes:
I'm not sure if this try is needed, or just use GCC #pragma instead. It's not a big issue, not sure if my way is proper or not.

Fix warning from [-Wfloat-equal]

---

src/lexer.l

Simply extended the lexer grammar to make `T_FIELD` also match underscore and hyphen (`[a-zA-Z][-_a-zA-Z0-9]+`).
Resolves #291.

Made output filters support fields with underscore or hyphen

---

examples/forge-socket/Makefile

cc -I../../lib/ -I../../forge_socket -Wall -g -O2 -fstack-protector-all --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -fPIC   -c -o forge-socket.o forge-socket.c
cc -I../../lib/ -I../../forge_socket -Wall -g -O2 -fstack-protector-all --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -fPIC   -c -o xalloc.o ../../lib/xalloc.c
cc -I../../lib/ -I../../forge_socket -Wall -g -O2 -fstack-protector-all --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -fPIC   -c -o logger.o ../../lib/logger.c
cc -I../../lib/ -I../../forge_socket -Wall -g -O2 -fstack-protector-all --param=ssp-buffer-size=4 -Wformat -Wformat-security -Werror=format-security -fPIC forge-socket.o xalloc.o logger.o -o forge-socket -lpcap -levent …

Compile forge-socket error

---

.travis.yml
INSTALL.md
src/CMakeLists.txt
src/fieldset.c
src/fieldset.h
src/probe_modules/module_dns.c

This addresses https://github.com/zmap/zmap/issues/301 by requiring that potentially unsafe strings be handled via the new fieldset operation fs_add_unsafe_string().
fs_add_unsafe_string() is designed to be used when you are supposed be given utf8 but the string may be malformed (e.g. you yanked it out of a DNS packet). fs_add_unsafe_string() will check if the string is a valid utf8 encoding. If not it will escape the offending byte as \u00XX.
A drawback here is we don't escape the escape character. This makes it impossible to differentiate between an escaped sequence and those bytes actually being in the string. Given that this is an extreme corner case (currently 1 server on the Internet, one protocol) I believe not altering the escape character is the right call. Especially given that …

Handle Unsafe utf8 strings

---

INSTALL.md

fatal error: unistr.h: No such file or directory when trying to compile without libunistring-devel installed.

Update missing dependencies on Fedora based systems

---

src/probe_modules/module_udp.c
src/probe_modules/module_udp.h

Fixes #343.
Tested by using the zmap-supplied `sip_options.tpl` template file as both a file and a template.  When used as a file, the UDP payload is literally the contents of this file,  uninterpolated, and there are no trailing nulls, incorrect IP or UDP header lengths or anomalies noticed by wireshark:
```
(with tcpdump running)
$  ./src/zmap -q -i en0 -s 5060 -p 5060 192.168.0.1 -M udp --probe-args=file:./examples/udp-probes/sip_options.tpl
May 06 09:33:32.032 [WARN] zmap: too few targets relative to senders, dropping to one sender
May 06 09:33:32.032 [INFO] zmap: output module: csv
May 06 09:33:32.032 [INFO] csv: no output file selected, will use stdout
09:33:32.040647 ac:bc:32:b6:29:67 > bc:14:01:57:0b:52, ethertype IPv4 (0x0800), length 464: 192.168.0.19.5060 > 192.168.0.1.5060: …
```

Correct length of templatized UDP payloads 

---

src/CMakeLists.txt

Use correct CMAKE dir variable to fix out-of-source builds.
Verified that in-source builds are still working.

Fix out-of-source builds

---

src/probe_modules/module_tcp_synackscan.c
src/probe_modules/module_tcp_synscan.c

Accepts additional packets as valid as part of the SYNACK scan module. This involves setting additional validation bits in the ACK Field (which we should have been doing to begin with) and checking them.
Also part of the PR is correcting how zmap validates RST packets for SYN scans. Per the RFC, in SYN-SENT you should accept SYN+0 as well as SYN+1 packets. We previously only accepted SYN+1
Rolled into this is fixing a few lines whitespace where spaces were used instead of tabs.

Accept additional synack RST responses, correct syn scan RST behavior

---

INSTALL.md

Original text:
```
Release builds shoudl be built with -DENABLE_LOG_TRACE=OFF.
```
Please fix `should` to *` should`*.

Fix a spelling error in INSTALL.md

---

src/recv-pfring.c
src/send-pfring.h
src/zmap.c

This fixes the 10 Gig support to compile against PF_RING 6.2. It may also work
with newer versions. Specifically, it updates for the new type of the
pf_ring_distribution_func callback, and accounts for pk_ring_zc_pkt_buf no
longer having the `data` field.
Fixes #350

Fix compatibility with newer PF_RING

---

src/zblacklist.1
src/zblacklist.1.html
src/zblacklist.1.ronn
src/zblacklist.c
src/zbopt.ggo.in

Closes #381
Previously we were reading an uninitialized in_addr struct resulting
in different behavior depending on unrelated options.
We now short circuit when we hit an invalid entry (preventing reading
uninitialized memory, and control printing with a new argument.
I also renamed the existing conf variable from ignore_errors to ignore_blacklist_errors, to match convention everywhere else.

Handle invalid zblacklist input, arg to toggle printing

---

CMakeLists.txt
lib/includes.h
lib/util.c
src/CMakeLists.txt
src/probe_modules/module_dns.c

I have tested this version of codes in NetBSD 7.0. `zmap` can be compiled successfully.

Add NetBSD compatibility code

---

src/get_gateway-linux.h

unsigned ints cant be less than 0, and the sizeof(ptr) != sizeof(static array)

Fix gateway mac detection on linux

---

src/probe_modules/module_dns.c

This adds support for multiple DNS questions via the syntax:
"A,example.com;AAAA,www.example.com"
To use this you must set --probes to match the number of questions
and --output-filter="" (or something non default) to avoid
filter_duplicates

Support for multiple DNS questions

---

src/output_modules/module_csv.c
src/state.h
src/zmap.c

only skip CSV header row when default output module not based on number of columns

---

CONTRIBUTING.md
INSTALL.md
README.md

It'll be easiest just to read the Markdown-rendered versions of these files:
* https://github.com/zmap/zmap/blob/cdz/doc-edits/README.md
* https://github.com/zmap/zmap/blob/cdz/doc-edits/INSTALL.md
* https://github.com/zmap/zmap/blob/cdz/doc-edits/CONTRIBUTING.md
Notably, I removed Mongo from the docs since we're removing it in 3.0.

Various minor improvements in readme/install/contributing

---

src/send.c

(Note: This branch has a bunch of debug and partial commits in it. Once approved let me squash and edit the commit msg down plz.)
This PR fixes a number of issues:
* `count` and `last_count` were type `uint32_t`. When sending multiple packets (`-P`) this could lead to overflow. They are now `uint64_t`
* We implicitly relied on `count > last_count` and `time > last_time`. These are now assertions (that would have caught the overflow above)
* Our carefully calculated `delay` (used for busy waiting) is thrown away on the first iteration through the loop due to a startup error (`count == 0`). This caused delay to begin at `1` and cause a send spike. This is fixed by not entering the delay adjustment clause on startup (`count == 0`)
* The behavior of our delay calculation code is... …

Fix packet rate limiting in send.c under specific conditions. Harden send.c

---

src/send.c

In #488 I stumbled with what I thought was a bug.  It isn't.  This PR is the result, which cleans up some comments in this regard and improves the debug output, which I've been using to help understand rate issues.

Clarify/improve rate and bandwidth-based comments and logging

---

src/probe_modules/module_udp.c

In the UDP probe module, packet length was set
in the per thread initialization instead of global
causing -B option to send at incorrect packet rate.
Also default packet length was 1, so changed to the
maximum to let it fail slower rather than faster.

Fixing #499 UDP bandwidth issue

---

src/probe_modules/module_dns.c
src/topt_compat.c
src/zbopt_compat.c
src/zitopt_compat.c
src/zopt_compat.c
src/ztopt_compat.c

It looks like there's been a buildup of gcc errors on Linux (which I suspect that we've missed because most of the devs are on Mac boxes and using clang).

fixing up warnings that have been showing up on linux systems

---

src/monitor.c
src/recv-pcap.c

I believe this resolves #518 
I tested this with the flags provided in #518 before these changes and confirmed the same behavior, after this fix I observed normal behavior.

Fix Monitor and Recv bug with Max results

---

src/ziterate.c

Following @dadrian's example in #469 
Before:
```
$  ./src/ziterate --shards 12345 -e 54321 --shard 1100 |wc -l
May 21 11:08:35.131 [FATAL] zmap: argument `shard' must be between 0 and 254
```
After:
```
$  ./src/ziterate --shards 12345 -e 54321 --shard 11000 |wc -l
347911
$  echo $(((2**32)/12345))  
347911
```

Allow ziterate to use up to 65535 shards

---

lib/blacklist.c

Currently we are getting a lot of errors like
`[ERROR] constraint: 'ec2-ww-xxx-yy-zz.compute-1.amazo' is not a valid IP address or hostname`
because we only read up to 32 bytes from each line of the blacklist -- while we obviously have hostnames that are much longer than that.
This patch will increase the maximum size to 255.

blacklisted hosts can be longer than 32 bytes

---

Dockerfile
lib/constraint.c

I believe this resolves #528 and I confirmed that this works in Docker.

Fix bug in prefix length check, typo

---

src/output_modules/module_redis_csv.c

Fixed a typo in redis-csv output module that will cause binary field
overwriting prior fields in the output.

Fixed issue #572

---

lib/blacklist.c

The default prefix length if none is given should be 32 and not 256, as
256 is not a valid prefix length.
Resolves #591.
This bug was introduced by 0e94a7cd7c3f4fd363af9c39cb882a218439491b
in PR #526.

Fix incorrect default prefix length for targets

---

CMakeLists.txt

The new pkgconfig file contains two include directories:
```
Cflags: -I${includedir} -I${includedir}/json-c
```
Apparently pkg_check_modules returns them as a semicolon-separated string ("CMake list"), which causes the build to fail when appended directly to `CMAKE_C_FLAGS`.
There's probably a proper way to handle this, please let me know if you know it.

Fix build against json-c 0.14

---

src/get_gateway-linux.h

Instead of only looking at the first routing table, try looping through
all of them.
Fixes #534

Try all routing tables in Linux get_gateway_linux.h

---

test/test_zblocklist.py

Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
Python 2 died on 1/1/2020.

Use print() function in both Python 2 and Python 3

---

.travis.yml

* `dist: bionic` fails on `Package 'libstdc++-4.9-dev' has no installation candidate`
* `dist: focal` fails because you cannot install legacy Python on it.

Travis CI: dist: xenial because Trusty is EOL

---

README.md

I think we've been dropped from most of these since we haven't done a stable release in so long, and 2.1.1 depends on old versions of generally unsupported software (including the Redis library)

Remove package managers from README

---

src/probe_modules/module_icmp_echo.c

👋 
The comparaison in case ICMP data is provided with the `hex:` prefix is wrong: the payload is compared with `"hex"` not the full argument. This simple fix makes it work.
Cheers!

Fix ICMP echo scan with `hex:` probe arg prefix not working

---

lib/blocklist.h
lib/constraint.c
lib/constraint.h
lib/csv.c
lib/csv.h
lib/includes.h
lib/lockfd.c
lib/lockfd.h
lib/logger.h
lib/pbm.c
lib/pbm.h
lib/queue.c
lib/queue.h
lib/random.h
lib/types.h
lib/util.c
lib/util.h
lib/xalloc.c
lib/xalloc.h
src/output_modules/module_json.h
src/probe_modules/packet.h
src/probe_modules/probe_modules.h
src/summary.h
src/topt_compat.c
src/utility.h

```
go run github.com/google/addlicense -c "Regents of the University of Michigan" -l apache src lib
```
I then manually removed the license from files we didn't actually own (or that we generated)

Add missing license headers

---

lib/util.c
lib/util.h
src/fieldset.c
src/fieldset.h
src/output_modules/module_csv.c
src/output_modules/module_json.c
src/output_modules/output_modules.h
src/state.h
src/zmap.c

This makes a few more functions operate on const char * so that we can
remove casts in zmap.c.

Remove casts from const char * to char *

---

lib/util.c
src/probe_modules/module_bacnet.c
src/probe_modules/module_dns.c
src/probe_modules/module_icmp_echo.c
src/probe_modules/module_icmp_echo_time.c
src/probe_modules/module_ntp.c
src/probe_modules/module_tcp_synackscan.c
src/probe_modules/module_tcp_synscan.c
src/probe_modules/module_udp.c
src/probe_modules/module_udp.h
src/probe_modules/module_upnp.c
src/probe_modules/probe_modules.h
src/send.c

Probe modules with dynamic output already needed to set `*buf_len`
during calls to `make_packet`. Not all probe modules did this. Some
opted to update the value of `probe_module.packet_length`. This is not
safe in a multithreaded invocation.
This commit forces all probe modules to update `*buf_len`, and replaces
the packet_length parameter with a max_packet_length, which is used for
bandwidth rate calculation as an upper bound. It is unclear if the rate
calculation works currently, but at least it's getting consistent input
now.

Ensure all probe modules set *buf_len

---

src/send.c

The send rate variable is only used when calculating sleep times for
"slow" rates. It was not correctly accounting for multiple probes.
Adding this in fixes the percent calculation and sends at the correct
rate.
Fixes #649

Fix slow send rate calculations

---

src/probe_modules/module_tcp_synackscan.c
src/probe_modules/module_tcp_synscan.c
src/probe_modules/packet.c
src/probe_modules/packet.h

For both synscan and synackscan, set MSS to 1450. This is the default
Linux MSS, and the option is required to be set for certain hosts to
respond.
Fixes #601

Set MSS to default Linux MSS in synscan modules

---

src/probe_modules/module_udp.c

In the current code it is not possible to pass `--probe-args=hex:..` to the `udp` probe module. The following error message is displayed:
```
udp: unknown UDP probe specification (expected file:/path or text:STRING or hex:01020304 or template:/path or template-fields)
```

Fix handling of hex UDP args.

---

src/probe_modules/module_ntp.c

The function is not called anywhere. The module's make_packet uses `udp_make_packet`.
The type of `ntp_make_packet` is also not compatible with `probe_make_packet_cb` any longer. For example the `size_t *buf_len` argument is missing.

Remove `ntp_make_packet` since it is dead code

---

src/probe_modules/module_udp.c

I was getting a segmentation fault due to this missing return.

udp_do_validate_packet - return after invalid packet

---

src/probe_modules/module_udp.c

Fixes the destination port substitution for UDP packet templates.
```
root@sandbox:~# zmap --version
zmap 2.1.0
root@sandbox:~# cat udp_template
dest_${DPORT}_source_${SPORT}
root@sandbox:~# tcpdump -A 'udp port 8888' &
[1] 20544
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
```
```
root@sandbox:~# zmap -M udp -p 8888 127.0.0.1 -S 127.0.0.1  --probe-args=template:./udp_template  -f saddr,data -o -
Jul 26 17:59:42.467 [WARN] zmap: too few targets relative to senders, dropping to one sender
Jul 26 17:59:42.679 [INFO] zmap: output module: csv
saddr,data
18:06:08.422581 IP localhost.46599 > localhost.8888: UDP, length 23
E..2.1................".....dest_46599_source_46599
.......
^C
```
```
root@sandbox:~# zmap -M udp -p 8888 127.0.0.1 -S 127.0.0.1 …
```

Fix template substitution for UDP module

---

src/monitor.c

Fixes #715.
If number of probes is greater than 1, then any scan above 50% will result in the multiplication in the given line to overflow. This triggers a false minimum comparison, yielding wildly incorrect scan time estimations.
The fix is to cast the 32 bit value to a uint64_t before multiplication, as is done for the other clauses above.
Before fix:
```
$~/repos/zmap$ ./src/zmap --dryrun -p 443 -n 100% -u updates.csv -l debug.log -r 60000 -v5 -P 1 > /dev/null
...
0:05 0% (17h left); send: 291944 58.5 Kp/s (58.4 Kp/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
$:~/repos/zmap$ ./src/zmap --dryrun -p 443 -n 100% -u updates.csv -l debug.log -r 60000 -v5 -P 2 > /dev/null
...
0:05 0% (14h left); send: 293616 60.3 Kp/s (58.7 Kp/s avg); recv: 0 0 p/s (0 p/s avg); …
```

Fix 32bit overflow in monitor.c (issue #715)

---

src/probe_modules/module_icmp_echo_time.c

Fixes inaccurate RTTs when using the `icmp_echo_time` module (https://github.com/zmap/zmap/issues/562).
This follows up on https://github.com/zmap/zmap/pull/607 which passes the pcap/pf_ring timestamp to the packet handler. The information was there but was seemingly never used.
This adds two fields to the output of the `icmp_echo_time` module based on the capture timestamp: `recv_timestamp_ts` and `recv_timestamp_ns`.
Test:
```bash
./src/zmap -M icmp_echo_time -O json 8.8.8.8 \
-f sent_timestamp_ts,sent_timestamp_us,timestamp_ts,timestamp_us,recv_timestamp_ts,recv_timestamp_ns > res.json
```
RTT with original timestamp:
```bash
jq '((.timestamp_ts * 1e6 + .timestamp_us) - (.sent_timestamp_ts * 1e6 + .sent_timestamp_us)) / 1e3' res.json
1044.48
```
RTT with link-layer timestamp:
```bash …
```

Store link-layer timestamp in icmp_echo_time module

---

src/zmap.c

Bugfix: Passing no port to ICMP module (or any module without a port requirement) causes segfault

---

src/zmap.1
src/zmap.1.ronn
src/zopt.ggo.in

- fixed a typo in man pages
- re-generated the man pages with `ronn` CLI tool
- verified that the changes took effect with `man zmap`
- fixed a typo in the `--help` text
- verified the changes took effect by re-compiling and running `zmap --version`

Fixed typos in man pages and --help text

---

.gitignore
src/zblocklist.1
src/zblocklist.1.html
src/ziterate.1
src/zmap.1
src/zmap.1.html
src/zmap.1.ronn
src/zopt.ggo.in
src/ztee.1
src/ztee.1.html

- added details to `--probes` to contrast with `--retries`
- re-generated manual pages with `make manpages`
- added `.DS_Store` to `.gitignore`. Looks like it can be auto-generated on MacOS, don't want that slipping into the repo

Update manual pages to add details to --probes to contrast with --retries

---

INSTALL.md

- updates the dependencies for `fedora` to use `Judy-devel` since that is the name of the pkg in the latest `fedora`
- added `gcc` since `cmake .` couldn't find a C compiler without that
In `fedora:latest`, `libjudy-devel` doesn't seem to be in the package manager
```shell
[root@91cc5934e0ff /]# sudo yum install cmake gmp-devel gengetopt libpcap-devel flex byacc json-c-devel libunistring-devel libjudy-devel
Last metadata expiration check: 0:00:12 ago on Thu Nov 16 23:09:57 2023.
No match for argument: libjudy-devel
Error: Unable to find a match: libjudy-devel
[root@91cc5934e0ff /]#
```
But if you use `Judy-devel`, it works. We also need `gcc` as well
```shell
[root@91cc5934e0ff /]# yum search Judy-devel
Last metadata expiration check: 0:24:10 ago on Thu Nov 16 23:09:57 2023. …
```

updated Fedora dependencies to having Judy-devel since the prior pkg doesn't exist in latest fedora

---

src/get_gateway-linux.h

It seems that patch bf5ed24c1535e0342631cf9ad904fa59720bc46b changed the way zmap finds the default interface.
It used to use `get_default_gw` to find the interface with the default route. Now it uses `pcap_lookupdev` which takes the first interface suitable for packet capture, but does not ensure that it has the default route.
This patch reverts to the old behavior and is consistent with `get_gateway-bsd.h`.

Use interface with default route on Linux

---

lib/util.c
lib/util.h
src/zblocklist.1
src/zblocklist.1.html
src/ziterate.1
src/ziterate.1.html
src/zmap.1
src/zmap.1.html
src/zmap.1.ronn
src/zmap.c
src/zopt.ggo.in
src/ztee.1
src/ztee.1.html

This should give us a more sane default, especially on hosts with less cores.
Ran on Mac, compiles and runs correctly
To test if it picks up cores correctly, ran on a Ubuntu VM with 2 cores, it detected this correctly.

Set default senders as min(4, number of cores on host)

---

src/send-bsd.h
src/send-linux.c
src/send.c

Fixes #765 , more details are available there.
Changes:
1. Don't error when `send_batch` is called with an empty batch
2. Don't call `send_batch` with `--dryrun` in `send_batch cleanup`
```
$ sudo ./src/zmap  -p 80 --source-mac=74:a6:cd:d3:07:df -n 65 -c 1                      
Jan 21 15:02:01.655 [INFO] zmap: By default, ZMap will output the unique IP addresses of hosts that respond successfully (e.g., SYN-ACK packet). This is equivalent to running ZMap with the following flags: --output-module=csv --output-fields=saddr --output-filter='success=1 && repeat=0' --no-header-row. If you want all responses, explicitly set an output module or set --output-filter="".
Jan 21 15:02:01.655 [INFO] dedup: Response deduplication method is full
Jan 21 15:02:01.684 [INFO] recv: duplicate responses will …
```

Don't error in send_cleanup with empty batches (like with `--dryrun`)

---

src/zmap.c

Prevents crash for `--batch` sizes of multiples of 256, which stored in `zconf.batch` of type `uint8_t` end up as 0.
/cc @phillip-stephens

Prevent --batch from overflowing the uint8_t it is being stored in

---

INSTALL.md
lib/includes.h
src/CMakeLists.txt
src/get_gateway-bsd.h

Fixes and modernisations for BSD `get_gateway` code:
- Fix `get_iface_hw_addr()` on macOS, where `--source-mac` was needed in at least some cases, depending on libdnet, by rewriting it using getifaddrs(3) in lieu of libdnet.  getifaddrs(3) is generally portable across all BSD variants and it had already been used for `get_iface_ip`.
- Fix `get_hw_addr()` on FreeBSD, where `--gateway-mac` was needed, by rewriting it using `sysctl(2)` in lieu of libdnet.
- While here, fix two file descriptor leaks and one memory leak in `get_default_iface` and `get_default_gw`.
- Remove the libdnet dependency; it had already been removed for Linux, now it is no longer needed for macOS / BSD either.
Tested on macOS Sonoma as well as FreeBSD 14.0.
(Apologies for extending the scope of an already open PR, but …

Multiple fixes for BSD get_gateway code, remove libdnet

---

CMakeLists.txt

This leftover bit was the result of a collision of two in-flight PRs. The last use of `_SYSTYPE_BSD` was removed along with libdnet in #772, while #771 at the same time added the `-D_SYSTYPE_BSD` to `CMakeLists.txt` in order to remove the need to manually define it when building.
`_SYSTYPE_BSD` is a rather archaic define.  libdnet might have used it for compat with now historical systems/compilers, but I do not think it served any purpose beyond that.  Certainly, modern FreeBSD, NetBSD and macOS do not reference it at all.  It seems safe to remove.

Stop defining the now defunct _SYSTYPE_BSD

---

src/get_gateway-bsd.h

Fix a BSD `get_hw_addr` failure path memory leak that I introduced in #772.

Fix mem leak on BSD get_hw_addr failure path

---

src/recv-pcap.c
src/send-mac.h
src/socket-bsd.c

- Implement IP layer mode on macOS using `socket(PF_INET, SOCK_RAW, IPPROTO_RAW)` and `setsockopt(IP_HDRINCL)`
- Teach recv-pcap to handle BSD loopback encapsulation as used by macOS `utun` interfaces
- While here fix file descriptor leaks in bpf failure paths
Deliberately ifdef'ed macOS-specific code with `__APPLE__` such that in the future, the code can be shared amongst macOS and BSDs lacking sendmmsg.  If/when I get around to implement sendmmsg for BSD, I'll likely propose to split send code into bsd-legacy and bsd-sendmmsg, instead of send-bsd and send-mac with largely duplicate code for the "no sendmmsg available" case.

Support IP layer mode on macOS

---

src/recv.c

- Avoid writing more than `sizeof(fake_eth_hdr) - sizeof(struct ether_header)` bytes to `&fake_eth_hdr[sizeof(struct ether_header)]`, avoiding overflow of `fake_eth_hdr`
- Ensure `buflen` matches effective amount of data in `bytes` after pointing `bytes` to `fake_eth_hdr`
Should fix zmap/zmap#580.

Fix size calculations to prevent overflowing fake_eth_hdr in IP layer mode

---

src/get_gateway-bsd.h

Fix two off-by-one errors in bounds checks that led to the last rt_msg getting skipped, which sometimes caused zmap to not find the ARP entry for the gateway IP address, depending on its location in the ARP table.  Bug introduced in #772.

Fix issue in BSD get_hw_addr where last ARP entry would be skipped

---

lib/cachehash.c
src/parser.y
src/recv.c
src/send.c

Fix benign compiler warnings on macOS/FreeBSD clang:
```
lib/cachehash.c:152:27: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
node_t *n = judy_get(ch, key, keylen);
^~~
```
```
lib/cachehash.c:166:27: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
node_t *n = judy_get(ch, key, keylen);
^~~
```
```
lib/cachehash.c:217:21: warning: passing 'const void *' to parameter of type 'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
JHSI(v_, ch->judy, key, keylen);
^~~
```
```
src/recv.c:104:17: warning: comparison of integers of different signs: 'uint32_t' (aka 'unsigned int') and 'int' …
```

Fix benign compiler warnings on macOS/FreeBSD clang

---

src/cyclic.c

With probability of roughly 1/group->prime, find_primroot() was allowing a candidate value of 0 through the checks, resulting in a scan that only sent one packet per send thread, all to index 0, because `shard->params.factor` ended up as 0.

Avoid isomorphism 0

---

src/socket-bsd.c

Noticed in testing this [PR](https://github.com/zmap/zmap/pull/778) that if the user forgets `sudo`, there were a bunch of errors printed on Mac. @droe had the exact same setup but wasn't seeing this behavior, which is odd. Either way, I think this fix makes sense. If you can't get a socket, you can't send packets, so this should be a fatal error, IMO.

phillip/781: elevate debug log if can't get a socket on bsd to fatal

---

src/shard.c

Prevents shard->current from wrapping around from 0 (`ZMAP_SHARD_DONE`) to -1 and causing an assertion failure in the constraint lookup code:
```
Assertion failed: (index < con->root->count), function constraint_lookup_index, file constraint.c, line 253.
```
This situation only manifested if one of the send threads happened to get a range containing no usable elements, which is extremely unlikely in normal ZMap use cases, but occurred relatively frequently when scanning only very few targets, such as a /29, using multiple send threads, i.e. #threads ≈ #targets.

Fix assertion failure when shard_roll_to_valid() iterates to the end

---

src/probe_modules/module_dns.c

Convert dns probe module to use proper stdbool booleans instead of uint8_t.
Paves the way for using stdbool in headers that are included by `src/probe_modules/module_dns.c`, removes the need for undefining bool for NetBSD, and is more consistent with existing other use of `bool` in ZMap's codebase.

Use stdbool instead of typedef uint8_t bool in dns probe module

---

src/probe_modules/module_dns.c

Fix two crashes in the DNS probe module's argument handling:
- Null pointer dereference on `--probe-module=dns` without `--probe-args`
- Null pointer dereference on `--probe-module=dns` with `--probe-args=""`

Fix two crashes in dns probe module args handling

---

src/shard.c

While working on the integration test PR, I noticed my tests around multiple ports were intermittently failing. After some investigation, I believe this is the fix. This just adds the check already present in `shard_get_next_target` [here](https://github.com/zmap/zmap/blob/main/src/shard.c#L185) to the `shard_roll_to_valid`.
My tests pass after this fix.

Fixed bug in the shard initialization w/ multi-port

---

src/send.c
src/send.h
src/state.h
src/zmap.c

I'd like to suggest to promote batch size to a uint16_t.  I am testing on 10GbE hardware on which batch size somewhere above 256 is currently a sweet spot (with netmap); the current uint8_t limits me to 255.  While there might be other perf improvements with bigger impact than what I see from batch size tuning, I see no real downside in allowing for a larger range of batch sizes.
Tested on macOS Sonoma and FreeBSD 14.0.

Bump batch size from uint8_t to uint16_t

---

README.netmap.md
src/recv-netmap.c
src/state.h
src/utility.h
src/zblocklist.1
src/zblocklist.1.html
src/ziterate.1
src/ziterate.1.html
src/zmap.1
src/zmap.1.html
src/zmap.1.ronn
src/zmap.c
src/zopt.ggo.in
src/ztee.1
src/ztee.1.html

Going into and leaving netmap mode causes the link to go down and up as
part of a PHY reset.  If the interface is connected to a switch with STP
enabled, then depending on port configuration, the switch might be
muting the port for as many as 30 seconds while the port goes through
the listening and learning STP states.
To work around this in situations where the switch cannot be
reconfigured, `--netmap-wait-ping` allows to wait for end-to-end ICMP
connectivity with an IP address before starting the scan.
Tested w/FreeBSD 14.0 on VM and bare metal.

netmap: Add --netmap-wait-ping to work around STP blocking ports temporarily

---

src/aesrand.c

The AES-128 PRNG construction produces 128 bits of pseudo-randomness per AES block encryption.  Use the full 128 bits instead of throwing half of the bits away.
As long as aesrand is not used for any per-packet randomness, speeding up aesrand_getword() won't matter much, so the need for this change might seem arguable.  With the old version of #798 that used aesrand_getword() for every packet, this change reduced the loss of send rate by about half.

Double aesrand_getword() performance by using full 128 bits

---

src/if-netmap-linux.c
src/probe_modules/packet.c
src/probe_modules/packet.h
src/recv.c

```
src/recv.c:103:17: warning: ‘static’ is not at beginning of declaration [-Wold-style-declaration]
103 |                 const static uint32_t available_space = sizeof(fake_eth_hdr) - sizeof(struct ether_header);
|                 ^~~~~
src/if-netmap-linux.c: In function ‘fetch_stats64’: src/if-netmap-linux.c:94:18: warning: ISO C99 doesn’t support unnamed structs/unions [-Wpedantic]
94 |                 };
|                  ^
src/probe_modules/packet.h: In function ‘check_dst_port’: src/probe_modules/packet.h:162:37: warning: suggest parentheses around comparison in operand of ‘^’ -Wparentheses]
162 |                 return (to_validate <= max ^ to_validate >= min);
|                         ~~~~~~~~~~~~^~~~~~
src/probe_modules/packet.c: In function ‘set_timestamp_option_with_nops’: …
```

Fix a number of benign compiler warnings on Linux/GCC

---

lib/queue.c
lib/queue.h
src/ztee.c

Make zqueue store a `void *` instead of a `char *`.
Remove internal strdup of data ptr in push_back; instead, take ownership of the pointer and move the strdup to the callsite in ztee.
This also fixes a one-off memory leak in ztee where first_line was never freed after getting pushed onto the queue.
While here, fix memory leaks in the unused get_front and get_back functions.
Generalisation of zqueue motivated by wanting to use zqueue for [droe/netmap-arp](https://github.com/droe/zmap/tree/droe/netmap-arp).

Generalise zqueue to non-string data pointers, fix memory leaks

---

src/recv-netmap.c
src/send-internal.h
src/send-netmap.c

In netmap mode, the OS network stack never gets to see incoming packets unless we explicitly forward them to the host rings; hence the kernel will not be responding to ARP requests.  To remove the need for static ARP entries on the gateway, respond to ARP requests from the gateway for any of the source IPs of the scan.
The recv thread can now submit packets for sending to send thread 0 via a zqueue.  This is used to respond to ARP requests that arrive after having let loose the send threads.  While still waiting for end-to-end connectivity with `--netmap-wait-ping`, ARP requests are responded to by sending directly from the recv thread, just like the ICMP Echo requests.
I did not see any significant netmap perf change from this at 10 GbE.
Tested on both FreeBSD and Linux.  Verified to …

netmap: Reply to ARP requests from gateway for scan source IPs

---

CMakeLists.txt
README.netmap.md
lib/CMakeLists.txt
lib/aes128.c
lib/aes128.h
src/aesrand.c
src/validate.c
src/zmap.c

Introduce aes128 library code that uses hardware accelerated AES on architectures where it's supported, and will fall back to the existing software AES (Rijndael) if built without hardware acceleration, or if hardware acceleration is not supported by the CPU at run-time.
For now hardware acceleration is opt-in and requires `-DWITH_AES_HW` cmake argument to build. Acceleration implemented for x86_64 (AES-NI) and arm64 (ARMv8 CE) using compiler intrinsics, no assembly.
Adopt new aes128 abstraction in validate and aesrand.  Invoke quick selftest at ZMap start, to ensure correct operation regardless of which AES implementation is being used.
On hardware configurations where scan rate is limited by CPU, hardware-accelerating AES can substantially improve scan rate, because packet validation as …

AES hardware acceleration using AES-NI and ARMv8 CE

---

README.netmap.md
src/zopt.ggo.in

- Improve structure and update text of `README.netmap.md`
- Mention netmap in help for `--batch` that claimed that it's only relevant to Linux

Improve netmap docs

---

src/probe_modules/module_ipip.c

Fix two UaF's where memory in `args` was accessed through `c` pointer after freeing `args`, silencing the respective compiler warnings on Linux/GCC.  The UaFs are on error paths as part of parsing the command line, and as such unreachable from malicious response packets.
While here:
- Remove dead code after `log_fatal()`
- Avoid interpreting percent chars in `ipip_usage_error`
- Replace a manual if/exit combo with an assertion
- Remove extra newlines in log strings

Fix use-after-free's in IPIP probe module

---

src/shard.c

Fixes issue where scan would not terminate when one of the sentinel values is outside the 48 bit range (`shard->params.last >= (1 << 48)`).  This can only happen with the largest group (p: 2^48 + 23) and would be more likely to happen with many threads / shards.
Testing performed:
- `test/test-shard.sh` and `test/test_big_group.sh` still succeed
- smoke tested with a couple of scans
Possibly root cause of #809.

Do not skip elements >= (1 << 48) w/o checking for sentinel

---

CMakeLists.txt
src/if-netmap-linux.c

I'd like to suggest bumping the C standard from GNU C99 to GNU C11.  C11 has been around for sufficiently long that I don't think there are substantial risks or portability limitations associated with targeting C11 anymore, and there seem to be zero changes to the codebase required.
Motivation is mainly support for static assertions (compile-time assertions).  On clang and GCC they do compile with GNU C99, but will emit compiler warnings that they need C11 on at least GCC.

Bump -std to gnu11 for static assertions

---

src/probe_modules/module_upnp.c
src/probe_modules/packet.h
src/recv-netmap.c
src/send-bsd.c
src/send-linux.c
src/send-netmap.c
src/send.c
src/send.h
src/state.h

This is a very arguable change, feel free to reject.  I'm seeing a consistent ~ 0.7 % send rate improvement with lower-end hardware at 10 GbE close to but not quite at max send rate.
- Change how batch is laid out in memory:  Since all access is one packet at a time and never all IPs or all lengths, lay out all fields pertaining to the same packet adjacent in memory, for sequential access (single array of packets with metadata instead of separate arrays for packet data, lengths and ips)
- Reduce `MAX_PACKET_SIZE` from 4k to 2k minus metadata, which is still way above the standard MTU of 1500 that we probably don't want to exceed in order to avoid IP fragmentation
Extra benefits:
- Arguably cleaner code for accessing the packets in batches (no manual offset calculations)
- Single …

Smaller MAX_PACKET_SIZE and better batch cache locality

---

src/probe_modules/module_bacnet.c
src/probe_modules/module_dns.c
src/probe_modules/module_icmp_echo.c
src/probe_modules/module_icmp_echo_time.c
src/probe_modules/module_ipip.c
src/probe_modules/module_ntp.c
src/probe_modules/module_tcp_synackscan.c
src/probe_modules/module_tcp_synscan.c
src/probe_modules/module_udp.c
src/probe_modules/module_upnp.c
src/probe_modules/probe_modules.h
src/recv-netmap.c
src/send-bsd.c
src/send-linux.c
src/send.c
src/send.h

- Switch from writing each packet in a single buffer, and copying that buffer into the batch, to directly letting the probe modules write into the batch.  To that end, split probe module's `thread_initialize` callback into `thread_initialize` and `prepare_packet`, allowing the latter to be called on each buffer in a batch.
- Remove the almost unused `ip` field from `batch->packets[]`, as it was only used on an error path of BSD's send code, and the IP can also be read from the packet data.  While removing the `ip` field, align the packet data in batch such that the IP headers start at a 32-bit boundary, speeding up 32-bit header field access.
These combined get me ~ 2.9 % send rate improvement, two thirds of which coming from the first change.  Again, I realize some or all of this may be …

Less copying, more batch optimisation

---

src/socket-linux.c
test/integration-tests/test_scan.py

Noticed while testing out #820 that the `--iplayer` option on Linux wasn't working. After trying several commits stretching back to December 2023, I guess this bug has been there this whole time. Thanks to @droe for the fix. Closes #821 
Changes
- Added integration test testing scanning known good ups with `--iplayer`
- Fixed bug so linux can open correct socket with `--iplayer`
Tests

Fix being unable to open an `IP layer` socket on Linux

---

src/zmap.c

Was testing something else on a 1 core VM and noticed that even if you put `-T 1`, you were warned you were using too many sending threads.
Tests
- Tested on 1 core VM with `-T 1` (no warning) and `-T 2` (warning)
- Tested on multi-core VM and behavior was as expected

Don't tell user to use 0 cores on machines with only 1 core

---

src/monitor.c
src/zmap.c

Not sure why any user would _want_ to use this many, but since we're using a `uint_8` to store the number of sending threads, `> 255` wraps around. This leads to an unexpected number of sending threads used, at least from a user's perspective that doesn't know this detail. Setting a `log_fatal` to prevent this.

Error out if user uses > 255 Sending Threads

---

src/probe_modules/module_dns.c
src/send-linux.c
src/send-linux.h
src/send.c

```
In file included from src/send-internal.h:23,
from src/send.c:31:
src/send-linux.h:25:27: warning: ‘sockaddr’ defined but not used [-Wunused-variable]
25 | static struct sockaddr_ll sockaddr;
|                           ^~~~~~~~
src/send.c: In function ‘send_run’:
src/send.c:457:30: warning: ‘attempts’ may be used uninitialized [-Wmaybe-uninitialized]
457 |         if (!zconf.dryrun && send_batch(st, batch, attempts) < 0) {
|                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/send.c:303:13: note: ‘attempts’ was declared here
303 |         int attempts = zconf.retries + 1;
|             ^~~~~~~~
src/probe_modules/module_dns.c: In function ‘dns_global_initialize’:
src/probe_modules/module_dns.c:637:25: warning: ‘__builtin_strncpy’ output truncated before terminating nul …
```

Fix more mostly benign Linux/GCC compiler warnings

---

src/monitor.c

Resolves #823 
Saw with an assert that _sometimes_, the `remaining_secs` was < 0, causing our % remaining calculation to go over 100.
```
Mar 15 19:48:19.739 [WARN] monitor: rest = 2.043692
zmap: /home/pstephens/zmap-dev/src/monitor.c:165: compute_remaining_time: Assertion `zconf.cooldown_secs - (now() - zsend.finish) >= 0' failed.
```
I'm not entirely sure how this is happening, but this fix seems both relatively reasonable and sufficient to prevent it happening again.

Capped percent complete in monitor.c

---

src/monitor.c

As the issue (#823) montioned, the status output lacks the final line, which is crucial **for certain monitoring systems that track scanning progress via status files**. As a result, these systems are currently unable to accurately capture the completion of the scanning process.
> For comprehensive background information, refer to issue #823.
> Prior to the proposed changes, the status output format is as follows:
```bash
real-time,time-elapsed,time-remaining,percent-complete,hit-rate,active-send-threads,sent-total,sent-last-one-sec,sent-avg-per-sec,recv-success-total,recv-success-last-one-sec,recv-success-avg-per-sec,recv-total,recv-total-last-one-sec,recv-total-avg-per-sec,pcap-drop-total,drop-last-one-sec,drop-avg-per-sec,sendto-fail-total,sendto-fail-last-one-sec,sendto-fail-avg-per-se …
```

Output the progress once more when the whole scan process finished

---

AUTHORS
src/monitor.c
test/integration-tests/test_dryrun_tcp.py
test/integration-tests/utils.py

It seems that when #831 was opened, this was run before #825  that capped the percentage complete (this is why I have 3 tests, 1 for the code the issue opener used, one for `main` and one for post-fix). 
Only real change is in `monitor.c` to factor in number of ports when calculating time remaining. Not considering this led to the percentage growing over 100%, ex: scanning 3 ports meant percentage complete would rise to 300%. I tried to make an integration test to test the `status_file` to make sure that the eta was non-increasing, the percentage complete was non-decreasing, etc. However, this can't be run with `--dryrun` and so the test was taking forever to run with `pytest`. Decided it wasn't necessary but refactored a bit in the `integration-tests` while I was there.
Using `be2b` …

Fix incorrect status ETA and percent complete for multi-port scans with `--list-of-ips` and `--rate`

---

src/probe_modules/probe_modules.c
src/probe_modules/probe_modules.h
src/recv.c

For every packet that ZMap receives it calls `gettimeofday()` in the receive thread to write the receive time to the output file. Instead, the already present timestamp in the PCAP header can be used which should save CPU cycles and lead to more accurate receive times.

Use libpcap timestamp information instead of calling gettimeofday() in receive thread

---

src/send.c

Thanks for maintaining the awesome ZMap.
I'd like to perform scans with a rate of 100pps. I've observed that ZMap consumes a lot of CPU in that case. However, if I increase the slow rate threshold in send.c (to maybe 200), everything is fine - would you like to merge this to main? 
Of course, don't merge if there is a profound reason of '50' being the current threshold.

Increase sending slow_rate threshold to 200 

---

src/probe_modules/module_tcp_synscan.c
src/probe_modules/module_tcp_synscan.h
src/probe_modules/packet.c

After some investigation, I realized that the hit-rates ZMap sees vary depending on TCP options. Sending options exactly as the major OS's send offers a consistent, measurable improvement in hit-rate. Of these, Windows-style packets are the smallest by 8 bytes.
I ran 3 trials over 10% of the IPv4 space and found median hit rates on port 80:
|                   TCP Options Style|            Hit-rate    |  Size of Packet   |Max. Packets-per-Second (millions)|
|---|---|---|---|
|No TCP options |1.305%.    |     46            |                1.488|
|Windows |  1.331%       |    52                     |      1.389|
|smallest-probes| 1.328%   |       46            |                1.488|
|Linux-style.        |1.330%.    |    60              |              1.276|
Based on this, I think using a …

Change default TCP options for SYNSCAN module to Windows-style and add "smallest-probes" option

---

.github/workflows/cmake.yml
.github/workflows/pytest.Dockerfile
.github/workflows/ubuntu-24.04.Dockerfile

With the release of Ubuntu 24.04, the way python wants you to install dependencies system-wide changed. The Dockerfile specified `ubuntu:latest` so we ran into this.
- Import python packages with `apt-get install python3-pytest` to install them system-wide
- Add new `ubuntu-24.04` test just for compilation for the new OS

Fix integration-tests Dockerfile, add new Ubuntu 24.04 compilation test

---

src/probe_modules/module_tcp_synscan.c

Update guidance in error message to list `smallest-probes` instead of `none` which no longer exists.
#855 changed `--probe-args=none` to `--probe-args=smallest-probes`, but the error message for unknown `--probe-args` arguments still lists `none` as a valid argument (which is especially confusing when using `--probe-args=none` results in guidance suggesting to use `none`).

Fix unknown probe-args guidance for none -> smallest-probes change

---

lib/constraint.c

Reduce the size of the precomputed array of prefixes from 4 MB to 1 MB in order to fit into the cache of CPUs with lower amounts of cache.  Improves send rate on systems where send rate is CPU/memory-bound and cache is limited.
With the default blocklist, this changes the array/tree tradeoff from 3702243328 IPs in radix array, 15104 IPs in tree to 3702194176 IPs in radix array, 64256 IPs in tree.  That _seems_ like a reasonable price to pay for the perf boost of reducing the memory footprint to one fourth.  On a system with 8 core Intel Atom, 8*2 MB L2 cache, 10 GbE NIC, netmap, AES-NI, before this change, send rate was 11% below what the NIC can do, while with this change, zmap pushes packets faster than the NIC can send them.  You may want to test this change on higher end systems …

Use less memory for constraint lookup radix cache

---

src/recv-pcap.c

More details in PR, closes #852 .
Before, there was a timing issue since the monitor thread could run twice in between two receive thread runs. By reducing this timeout on the receive thread, this should prevent that from happening. 
Ran a scan and no longer see 0 p/s at line 43.
```
0:00 0%; send: 0 0 p/s (0 p/s avg); recv: 0 0 p/s (0 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.00%
0:01 2%; send: 10394 10.4 Kp/s (9.99 Kp/s avg); recv: 125 125 p/s (120 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.20%
0:02 4%; send: 20394 10.00 Kp/s (9.99 Kp/s avg); recv: 250 125 p/s (122 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.23%
0:03 6%; send: 30400 10.0 Kp/s (9.99 Kp/s avg); recv: 377 127 p/s (123 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.24%
0:04 8%; send: 40151 9.75 Kp/s (9.93 Kp/s …
```

Decreased pcap_timeout to prevent monitor timing issue

---

src/monitor.c

Closes #863 
Used `git bisect` to find this bug, looks like it's been in the code since 2021. (introduced in commit `a66169`).
We want to calculate hit-rate using the de-duplicated success packets. By using `filter_success`, the default behavior is to not de-duplicate responses. This led to the wild hit-rates.
`main`
```
$ cmake . && make -j4 && sudo ./src/zmap -p 80 -n 1000000 -B 100M -o /dev/null -c 5 -i enp0s8 --output-fields="*"
...
0:13 100% (0s left); send: 1000000 done (137 Kp/s avg); recv: 39246 0 p/s (3.01 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 3.92%
```
`Phillip/863` (with fix)
```
$ cmake . && make -j4 && sudo ./src/zmap -p 80 -n 1000000 -B 100M -o /dev/null -c 5 -i enp0s8 --output-fields="*"
...
0:13 100% (0s left); send: 1000000 done (136 Kp/s avg); recv: 13290 0 p/s …
```

Have monitor thread calculate hitrate using unique success packets, not filtered success packets

---

src/recv-pcap.c

This reverts commit 957010f017c023030b41f14d56b535cd9c998062.
It looks like this caused #868, reverting this until I can find a fix to satisfy both this and #852

Revert "Decreased pcap_timeout to prevent monitor issue ..."

---

src/probe_modules/module_tcp_synscan.c
src/recv-pcap.c

This fixes the bug opened in #868. The cause was if a packet came back with a TCP option in which the length was 0 (this does not conform to the spec ofc), the callback would be stuck in the loop forever. 
It also reverts the change I made in #869 that fixed PR #862 since that was not the root cause like I thought it was.
I'll close the PR #870 (which reverted the TCP options commit until I could figure out why it broke) since we should all be good now.
With the new fix, a large scan doesn't get stuck like it did AND we don't have the 0 rec/sec message in the monitor thread every 43 seconds.
```
0:41 67% (20s left); send: 102299450 2.40 Mp/s (2.49 Mp/s avg); recv: 1334110 31.5 Kp/s (32.5 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.30%
0:42 69% (19s left); send: 104799774 2.50 Mp/s …
```

Add sanity-check to TCP options for loop

---

src/probe_modules/module_tcp_synscan.c

Add full length checking to catch more types of malformed TCP options. Specifically, stop parsing options when the option's length field itself lies outside of the TCP header, or when the indicated length of the option extends beyond the end of the TCP header, or when an option has an unexpected length.
Basically a more thorough, more defensive version of the fix in #871, that will additionally prevent some classes of malformed TCP options from generating spurious fields with bad data in results.
Tested by verifying results are still the same for some test networks; did not do a full before/after diff for 0.0.0.0/0.
/cc @ogasser @phillip-stephens

More robust parsing of TCP options

---

src/recv-pfring.c
src/send-pfring.h
src/socket-pfring.c
src/zmap.c

Set zconf.data_link_size to unbreak the receive code and implement send_batch for PF_RING to unbreak the send code.  While here, also fix compiler warnings in PF_RING code.
Fixes #833.  Fixes #694.  Conflicts with #812.  (Feel free to remove PF_RING instead of fixing it.)
Tested in a VM, and seems to work fine, results and hit rate look good.  I don't have spare 10G hardware to install Linux on, so I cannot tell if ZMap with PF_RING is still able to send at 10G wire speed or not.

Unbreak PF_RING

---

src/recv-pfring.c

On empty queue, return after the brief sleep instead of looping.  This lets the outer loop check its termination condition.
Fixes bug where a PF_RING based scan would not terminate even after the cooldown timer expires, until there are extra incoming packets breaking the inner loop.

PF_RING: Do not delay termination by waiting for packets forever

---

lib/util.c
lib/util.h
src/state.h
src/summary.c
src/ziterate.1
src/ziterate.1.html
src/ziterate.c
src/zmap.1
src/zmap.1.html
src/zmap.1.ronn
src/zmap.c
src/zopt.ggo.in
test/integration-tests/test_dryrun_tcp.py
test/integration-tests/zmap_wrapper.py

This manifested both in debug messages and in the ETA remaining un-changed when you use more than 1 port with this flag.
Single Port, 1% of address space
```
sudo ./src/zmap -B 100M -o "/dev/null"  --verbosity=5 -n 1% -p 80
...
Jul 02 23:08:51.018 [DEBUG] iterator: max targets is 42949672
...
0:05 2% (5m16s left); send: 691206 139 Kp/s (137 Kp/s avg); recv: 8975 2.03 Kp/s (1.78 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 1.30%
```
2 Ports, 1 % of address space
```
sudo ./src/zmap -B 100M -o "/dev/null"  --verbosity=5 -n 1% -p 80-81
...
Jul 02 23:09:35.911 [DEBUG] iterator: max targets is 42949672
0:05 2% (5m21s left); send: 683403 135 Kp/s (135 Kp/s avg); recv: 4851 987 p/s (960 p/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.71%
```
```
~/zmap-dev on  phillip/max-targets-percent-help! …
```

the `--max-targets` flag with a percent wasn't respecting multi-ports

---

Dockerfile

When this Dockerfile was last edited, `Ubuntu 22.04` hadn't been released yet. This PR bumps the base image and package versions.

Bump docker base image and relevant packages

---

src/zmap.c

Currently, when giving any source port range (larger than a single port), zmap will return the message:
E.g.:
```
[...]
[WARN] zmap: ZMap is configured to use a relatively small number of source ports (fewer than 10x the number of probe packets per target ip/port), which limits the entropy that ZMap has available for  validating responses. We recommend that you use a larger port range.
```
This is due to the inequality sign being flipped. Also see #736.

Fix source port range size warning

---

CMakeLists.txt
src/zmap.c

Closes #894 
If someone had installed zmap prior to changing the `blacklist` -> `blocklist`, they may have an existing `/etc/zmap/blacklist.conf` file. If this file had been changed or had any modifications in it, it will not be respected after installing the latest ZMap. The fix is to rename the existing file (if it exists) to the expected `etc/zmap/blocklist.conf`,
Additionally, (and what I believe caused #894), the contents of `zmap.conf` would have been 
```
blacklist-file "/etc/zmap/blacklist.conf"
```
If the `zmap.conf` file exists and contains that string, we'll replace it with:
```
blocklist-file "/etc/zmap/blocklist.conf"
```
Also fixed a typo.
Notice how there are both a `blacklist.conf` and a `blocklist.conf`
```
276f9edbd3c2# mkdir /etc/zmap
276f9edbd3c2# echo "hello" > …
```

Handle upgrade path for blacklist to blocklist

---

.github/workflows/ubuntu-18.04.Dockerfile
.github/workflows/ubuntu-20.04.Dockerfile
.github/workflows/ubuntu-22.04.Dockerfile

@amirian28 brought to my attention that our tests to ensure we don't break compilation on various generations of Ubuntu weren't working as designed.
This PR brings the docker base version in line with what the test is supposed to be testing.

Fixes ubuntu docker base image versions in github tests

---

src/probe_modules/module_bacnet.c
src/probe_modules/module_dns.c
src/probe_modules/module_ipip.c
src/probe_modules/module_ntp.c
src/probe_modules/module_tcp_synackscan.c
src/probe_modules/module_tcp_synscan.c
src/probe_modules/module_udp.c
src/probe_modules/module_upnp.c
src/probe_modules/probe_modules.h
src/state.h
src/validate.c
src/zmap.1
src/zmap.1.html
src/zmap.1.ronn
src/zmap.c
src/zopt.ggo.in

The udp module is the only module that has source port validation off by default. This flag (`--validate-source-port`) allows the user to override this behavior and perform source port validation.

Add source port validation CLI option and associated code to UDP module

---

src/send.c

Resolves #903 
Thanks to @huxcrux for helping to debug this issue that I was having difficulty reproducing locally. 
The bug he saw was that sometimes, ZMap would not obey the `--rate` limit set in the CLI. After investigation, the issue is [here](https://github.com/zmap/zmap/blob/main/src/send.c#L336). The adaptive timing code uses an adaptive delay to ensure the send rate stays near the user's desired rate. 
This code works in most circumstances, however if some outside influence (other processes in @huxcrux's case were having contention on the core, when he used `--cores=` to pin ZMap, the effect was far reduced) prevents ZMap from sending at the desired rate, this adaptive delay will decrease to attempt to send faster. If ZMap is continually prevented from sending at the desired rate, …

[Bug] Fix ZMap not obeying `--rate` edge case

---

src/summary.c

@annalittle reported that she was still seeing integer overruns in the `--metadata-file`. This fix should address this, missed updating the `json_object_new_...` to match type.

Match JSON function to variable type

---

src/shard.c

Resolves #911 
Command on 5B targets- `sudo ./src/zmap -T 1 -B 2G -p 80-84 -o /dev/null --cores=0,1,2 --status-updates-file=/tmp/911-uint32.80-84.status -n 5000000000` 
```
15:13 14% (1h33m left); send: 699658367 764 Kp/s (766 Kp/s avg); recv: 2291532 2.58 Kp/s (2.51 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.33%
15:14 14% (1h33m left); send: 700450367 792 Kp/s (766 Kp/s avg); recv: 2294078 2.54 Kp/s (2.51 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.33%
15:15 14% (1h33m left); send: 701237631 787 Kp/s (766 Kp/s avg); recv: 2296795 2.72 Kp/s (2.51 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.33%
15:16 14% (1h33m left); send: 702027647 790 Kp/s (766 Kp/s avg); recv: 2299372 2.58 Kp/s (2.51 Kp/s avg); drops: 0 p/s (0 p/s avg); hitrate: 0.33%
15:17 14% (1h33m left); send: …
```

Missed a uint32

---

.github/workflows/scan_coverage.yml
.github/workflows/scan_coverage_pytest.Dockerfile

This PR fixes the daily scan coverage test with `--fast-dryrun`. The old docker image is arm only so we'll need to remove so it runs on the x86 VMs from Github Actions.
Ran a manual action to verify - https://github.com/zmap/zmap/actions/runs/12362461674

use the x86 ubuntu dockerfile base image, should fix failing daily test

---

src/if-netmap-bsd.c
src/if-netmap-linux.c
src/if-netmap.h

In 94867b0, the global counters zrecv.pcap_recv, .pcap_drop and .pcap_ifdrop were enlarged from uint32_t to uint64_t.  This resulted in pointer mismatches in the netmap code that updates those counters, and still expected 32-bit counters.
Going full 64-bit also removes the need to truncate netmap's internal 64-bit counters to 32 bits.

netmap: Fix if_get_stats to use uint64_t to match recent globals change

---

src/recv.c

Fix the size of the validation buffer in the recv code to be `uint32[4]`, not `uint32[16]`.  The new size matches what the send code uses, and the buffer size `validate_gen` expects and writes.

Fix size of recv validation from uint32[16] to uint32[4]

---

.github/workflows/cmake.yml

The GH Ubuntu 20.04 runner will be [deprecated](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/) and this test will begin failing. We already have an `Ubuntu 20.04` compilation test so updating this shouldn't have any negative effects.

Update built ubuntu GH runner to use latest rather than 20.04

---

.github/workflows/cmake.yml

This should resolve our `cmake.yml` CI, and keep this badge from showing an ominous "Failing"

Fix Failing FreeBSD CI
