src/zblacklist.1.ronn
src/ztee.1.ronn

Closes #286 
From Debian with love :heart:

Add generating of a NAME section in mans

---

src/CMakeLists.txt
src/probe_modules/module_bacnet.c
src/probe_modules/module_bacnet.h
src/probe_modules/module_udp.c
src/probe_modules/module_udp.h
src/probe_modules/probe_modules.c

Do not merge yet, just creating this for tracking purposes.

Add BACNet support

---

CMakeLists.txt
lib/util.c
src/get_gateway.c
src/send.c

Hi,
This patch adds DragonFly BSD support.

Add DragonFly BSD support

---

src/ziterate.1
src/ziterate.1.html
src/ziterate.1.ronn

ziterate to have a man file

---

lib/logger.c
src/zmap.c

Only log to syslog when enabled

---

src/zblacklist.c
src/zbopt.ggo.in
src/ziterate.c
src/zitopt.ggo.in

Add --disable-syslog to zblacklist and ziterate

---

src/zmap.c

Sane default cli

---

src/send.c
src/zmap.1.ronn

packets per second is _actually_ packets per second now instead of IPs… per second

---

src/send-linux.h

Remove unnecessary call to ioctl

---

src/probe_modules/module_icmp_echo.c
src/probe_modules/module_icmp_echo_time.c

This adds validation to the ICMP validation to the RTT scan, and also extends validation to use both ICMP id and sequence number.

Improved ICMP validation

---

src/probe_modules/module_icmp_echo.c
src/probe_modules/module_icmp_echo_time.c

I reverted my changes and rebased my zmap fork to continue working on the upstream zmap version (I think this also led to the PR getting closed automatically -- I didn't manually close it). Then I changed the ip_inner line and make'd zmap successfully. Hope this works now.

Continue: Extracting IP header from ICMP error message payload #420

---

src/monitor.c

Don't squash status_updates_file descriptor names

---

src/get_gateway-bsd.h

Cleanup warnings on FreeBSD

---

src/probe_modules/module_udp.c
src/probe_modules/probe_modules.h

Check if returned UDP packet is blacklisted

---

INSTALL.md
README.md
src/topt.ggo.in
src/ztee.1
src/ztee.1.html
src/ztee.1.ronn

Closes #429.
While documenting ZTee's CSV processing and raw mode, I also identified and corrected some inconsistencies between the manpage and ztee's actual flags.

Consistently document ZTee CLI flags

---

indent.sh
src/send.c

This file was totally screwed up.

Run GNU `indent -kr -i8 src/send.c`

---

src/iterator.c
src/iterator.h
src/shard.c
src/shard.h
src/state.h
src/zmap.c
test/test-shard.sh

Allow up to 65535 shards

---

src/probe_modules/module_upnp.c

A notable population of upnp devices respond using a non-standard srcport.
This commit removes the check for srcport == targetport for the validity checks,
leaving the decision of validity to the packet processor.

Be less strict on filtering UPnP probe responses

---

src/cyclic.c

Fixes #586
Co-Authored-By: @rstrullu

Prevent overflow in unlikely seed generation

---

src/validate.c

validate gen thraed safe

---

src/recv-pfring.c
src/zmap.c

Relates to issue https://github.com/zmap/zmap/issues/636
Might be a cleaner way of passing the timespec back though.

Fix PF_RING support

---

src/get_gateway-bsd.h
src/get_gateway-linux.h
src/send.c

Assign requested address message

---

.github/workflows/docker-publish.yml
Dockerfile

* Use multi-stage building to reduce image size
* Add GitHub Action to automatically publish image on [GitHub container registry](https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages)

build: improve Dockerfile

---

lib/logger.c
lib/logger.h
lib/util.c
lib/util.h
src/iterator.c
src/monitor.c
src/recv.c
src/send.c

Ipinfo clock monotonic

---

src/send-linux.h
src/send.c
src/zmap.c

log_fatal on bad send

---

INSTALL.md

Also mention pkg-config as a dependency (since, it is).

Update INSTALL.md with notes for installing via MacPorts.

---

src/probe_modules/packet.h
src/zmap.c

Warning about packet streams and fixed dst port validation

---

src/zopt.ggo.in

Update `--help` text to use new `--allowlist-file` parameter

---

README.md

A small handful of README text consolidations.

Small README Updates

---

src/send.c

@zakird noticed we have an unused variable, this removes that.

Removed unused idx variable

---

.github/workflows/cmake.yml
.github/workflows/ubuntu-16.04.Dockerfile
.github/workflows/ubuntu-18.04.Dockerfile
.github/workflows/ubuntu-20.04.Dockerfile
.github/workflows/ubuntu-22.04.Dockerfile

This should help us prevent releasing code (like #808 ) that works on the latest kernel but not older versions at least for Ubuntu.

Testing: added compilation tests for all Ubuntu LTS versions >= 16.04

---

src/probe_modules/module_tcp_synscan.c

This adds parsing of the following TCP options (when present) to the `synscan` module:
* MSS option
* Window scale option
* SACK permitted option
* Timestamp option value (`ts_val`)
* Timestamp option echo reply (`ts_ecr`)

Add TCP options parsing in synscan module

---

CHANGELOG.md
README.md

Forgot to update the CHANGELOG and README before tagging the release

bump CHANGELOG and README for new release

---

CHANGELOG.md
README.md

Tried releasing a patch release but a docker GitHub action doesn't seem to like that format. We'll just push a bug fix version.

Bump release version to v.4.1.1 and update the README and CHANGELOG

---

CHANGELOG.md
README.md

Prepares for releasing a new v4.3.3 release

Bump version in README and add changes to CHANGELOG
